services:
  postgres2:
    container_name: itemdb
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: itemdb
    volumes:
      - postgres:/data/postgres
    ports:
      - 5434:5432
    networks:
      - foundit-network
    restart: unless-stopped

  itemservice:
    build :
      context: .
      dockerfile: Dockerfile    
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5434/itemdb
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8082:8082
    depends_on:
      - postgres2
    networks:
      - foundit-network
    
networks:
  foundit-network:
    driver: bridge

volumes:
  postgres:
    driver: local