services:
  itemservice:
    build :
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/itemdb
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8082:8082
    networks:
      - foundit-network

networks:
  foundit-network:
    driver: bridge

volumes:
  postgres:
    driver: local